// ============================================
// APL TILBUDSANALYSE 2025 - OPPDATERT DATA
// Kilde: Tilbudsanalyse_APL_2025_NOVEMBER_NY_v2.xlsx
// Periode: 01.01 - 30.11.2025
// Sist oppdatert: 2025-12-01
// ============================================

const DATA = {
    // Metadata
    metadata: {
        periode: "01.01 - 30.11.2025",
        sistOppdatert: "2025-12-01",
        kilde: "Tilbudsanalyse_APL_2025_NOVEMBER_NY_v2.xlsx"
    },

    // ============================================
    // HOVEDTALL 2025
    // ============================================
    tilbud2025: {
        totalt: 701,
        vunnet: { antall: 312, verdi: 343.41, timer: 4222 },
        tapt: { antall: 181, verdi: 379.69, timer: 5525 },
        direkte: { antall: 208, verdi: 51.8, timer: 628.5 },

        tilslagAntall: 63.3,
        tilslagVerdi: 47.5,
        tilslagInklDirekteAntall: 74.2,
        tilslagInklDirekteVerdi: 51,

        totaleTilbudTimer: 10375.5,
        totalTilbudskostnad: 6.225,

        realisertVerdi: 395.21,
        tilbudskostAvRealisert: 1.6
    },

    // Timer-detaljer
    timerDetaljer: {
        tilbudVunnet: 4222,
        tilbudTapt: 5525,
        tilbudDirekte: 628.5,
        totalt: 10375.5
    },

    // Timer per tilbud (gjennomsnitt)
    timerPerTilbud: {
        vunnet: 13.5,
        tapt: 30.5,
        direkte: 3
    },

    // ============================================
    // HISTORISK UTVIKLING
    // ============================================
    historisk: {
        tilbudMarkedProsent: [
            { aar: 2018, prosent: 7.2 },
            { aar: 2019, prosent: 8.1 },
            { aar: 2020, prosent: 9.7 },
            { aar: 2021, prosent: 7.2 },
            { aar: 2022, prosent: 7.5 },
            { aar: 2023, prosent: 8.5 },
            { aar: 2024, prosent: 7.5 },
            { aar: 2025, prosent: 7.3, estimert: true }
        ],
        maal2026: 7.0
    },

    // ============================================
    // DIVISJONSSAMMENLIGNING
    // ============================================
    divisjoner: {
        sammenligning2024: [
            { navn: "APL", tilbudMarkedProsent: 7.5 },
            { navn: "Infrastruktur", tilbudMarkedProsent: 4.5 },
            { navn: "Arkitektur & Bygg", tilbudMarkedProsent: 5.0 }
        ],
        sammenligning2025: [
            { navn: "APL", tilbudMarkedProsent: 7.3 },
            { navn: "Infrastruktur", tilbudMarkedProsent: 4.3 },
            { navn: "Arkitektur & Bygg", tilbudMarkedProsent: 4.8 }
        ]
    },

    // ============================================
    // ST�RRELSER - sortert etter tilbudsverdi
    // ============================================
    storrelser: [
        { navn: "0 - 100 000", vunnet: 87, tapt: 14, direkte: 108, antall: 209, timer: 212, tilslag: 86.1, verdiVunnet: 4.86, tilbudskostAvRealisert: 1.4 },
        { navn: "100 000 - 300 000", vunnet: 62, tapt: 35, direkte: 36, antall: 133, timer: 1079.5, tilslag: 63.9, verdiVunnet: 13.18, tilbudskostAvRealisert: 3.6 },
        { navn: "300 000 - 700 000", vunnet: 44, tapt: 30, direkte: 19, antall: 93, timer: 1222.5, tilslag: 59.5, verdiVunnet: 19.75, tilbudskostAvRealisert: 2.9 },
        { navn: "700 000 - 1 500 000", vunnet: 35, tapt: 37, direkte: 10, antall: 82, timer: 2719.5, tilslag: 48.6, verdiVunnet: 35.34, tilbudskostAvRealisert: 4.1 },
        { navn: "1 500 000 - 3 000 000", vunnet: 17, tapt: 18, direkte: 6, antall: 41, timer: 1318.5, tilslag: 48.6, verdiVunnet: 36.24, tilbudskostAvRealisert: 1.8 },
        { navn: "3 000 0000 - 10 000 000", vunnet: 6, tapt: 11, direkte: 0, antall: 17, timer: 974, tilslag: 35.3, verdiVunnet: 39.2, tilbudskostAvRealisert: 1.7 },
        { navn: "> 10 0000 0000", vunnet: 2, tapt: 11, direkte: 0, antall: 13, timer: 689, tilslag: 15.4, verdiVunnet: 70, tilbudskostAvRealisert: 0.7 }
    ],

    // ============================================
    // REGIONER
    // ============================================
    regioner: [
        { navn: "Analyse, plan og landskap divisjonsledelse", vunnet: 0, tapt: 14, direkte: 0, antall: 14, timer: 568, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Analyse, plan og landskap nord/midt", vunnet: 43, tapt: 26, direkte: 31, antall: 100, timer: 1552.5, tilslag: 62.3, verdiVunnet: 59.66, tilbudskostAvRealisert: 1.7 },
        { navn: "Analyse, plan og landskap sør", vunnet: 94, tapt: 41, direkte: 112, antall: 247, timer: 2443.5, tilslag: 69.6, verdiVunnet: 57.36, tilbudskostAvRealisert: 2.2 },
        { navn: "Analyse, plan og landskap vest", vunnet: 62, tapt: 34, direkte: 11, antall: 107, timer: 1488, tilslag: 64.6, verdiVunnet: 46.83, tilbudskostAvRealisert: 2.1 },
        { navn: "Analyse, plan og landskap øst", vunnet: 112, tapt: 66, direkte: 53, antall: 231, timer: 4323.5, tilslag: 62.9, verdiVunnet: 123.57, tilbudskostAvRealisert: 2.1 }
    ],

    // ============================================
    // KONTORER - sortert etter timer (h�yest f�rst)
    // ============================================
    kontorer: [
        { navn: "Sandvika", region: "�st", vunnet: 63, tapt: 48, direkte: 44, antall: 155, timer: 3062.5, snittTimer: 19.8, tilslag: 56.8, verdiVunnet: 81.27, tilbudskostAvRealisert: 2.1 },
        { navn: "Bergen", region: "vest", vunnet: 39, tapt: 23, direkte: 3, antall: 65, timer: 1238.5, snittTimer: 19.1, tilslag: 62.9, verdiVunnet: 30.68, tilbudskostAvRealisert: 2.8 },
        { navn: "Arendal", region: "s�r", vunnet: 25, tapt: 11, direkte: 11, antall: 47, timer: 1100.5, snittTimer: 23.4, tilslag: 69.4, verdiVunnet: 11.6, tilbudskostAvRealisert: 5.1 },
        { navn: "Trondheim", region: "nord/midt", vunnet: 27, tapt: 16, direkte: 26, antall: 69, timer: 1025.5, snittTimer: 14.9, tilslag: 62.8, verdiVunnet: 42.35, tilbudskostAvRealisert: 1.5 },
        { navn: "Oslo", region: "�st", vunnet: 19, tapt: 13, direkte: 1, antall: 33, timer: 959.5, snittTimer: 29.1, tilslag: 59.4, verdiVunnet: 17.12, tilbudskostAvRealisert: 3.9 },
        { navn: "Tønsberg", region: "ukjent", vunnet: 21, tapt: 10, direkte: 13, antall: 44, timer: 525, snittTimer: 11.9, tilslag: 67.7, verdiVunnet: 12.02, tilbudskostAvRealisert: 2.6 },
        { navn: "Skien", region: "s�r", vunnet: 13, tapt: 7, direkte: 30, antall: 50, timer: 380, snittTimer: 7.6, tilslag: 65, verdiVunnet: 7.22, tilbudskostAvRealisert: 2.7 },
        { navn: "Hamar", region: "�st", vunnet: 14, tapt: 7, direkte: 7, antall: 28, timer: 372, snittTimer: 13.3, tilslag: 66.7, verdiVunnet: 16.83, tilbudskostAvRealisert: 1.3 },
        { navn: "Ås", region: "ukjent", vunnet: 11, tapt: 4, direkte: 0, antall: 15, timer: 309.5, snittTimer: 20.6, tilslag: 73.3, verdiVunnet: 60.02, tilbudskostAvRealisert: 0.4 },
        { navn: "Kristiansand", region: "s�r", vunnet: 22, tapt: 11, direkte: 17, antall: 50, timer: 307, snittTimer: 6.1, tilslag: 66.7, verdiVunnet: 21.77, tilbudskostAvRealisert: 0.8 },
        { navn: "Stavanger", region: "vest", vunnet: 21, tapt: 11, direkte: 8, antall: 40, timer: 196, snittTimer: 4.9, tilslag: 65.6, verdiVunnet: 9.05, tilbudskostAvRealisert: 1.2 },
        { navn: "Tromsø", region: "ukjent", vunnet: 7, tapt: 4, direkte: 2, antall: 13, timer: 188, snittTimer: 14.5, tilslag: 63.6, verdiVunnet: 14.95, tilbudskostAvRealisert: 0.8 },
        { navn: "Drammen", region: "�st", vunnet: 6, tapt: 6, direkte: 1, antall: 13, timer: 152.5, snittTimer: 11.7, tilslag: 50, verdiVunnet: 4.33, tilbudskostAvRealisert: 2.4 },
        { navn: "Mo i Rana", region: "nord/midt", vunnet: 2, tapt: 3, direkte: 1, antall: 6, timer: 129.5, snittTimer: 21.6, tilslag: 40, verdiVunnet: 0.62, tilbudskostAvRealisert: 13.6 },
        { navn: "Ålesund", region: "ukjent", vunnet: 2, tapt: 2, direkte: 0, antall: 4, timer: 129.5, snittTimer: 32.4, tilslag: 50, verdiVunnet: 0.88, tilbudskostAvRealisert: 10.3 },
        { navn: "Kongsberg", region: "�st", vunnet: 5, tapt: 2, direkte: 14, antall: 21, timer: 109, snittTimer: 5.2, tilslag: 71.4, verdiVunnet: 0.93, tilbudskostAvRealisert: 1.5 },
        { navn: "Molde", region: "nord/midt", vunnet: 5, tapt: 1, direkte: 1, antall: 7, timer: 59.5, snittTimer: 8.5, tilslag: 83.3, verdiVunnet: 0.86, tilbudskostAvRealisert: 3.7 },
        { navn: "Leikanger", region: "vest", vunnet: 2, tapt: 0, direkte: 0, antall: 2, timer: 53.5, snittTimer: 26.8, tilslag: 100, verdiVunnet: 7.1, tilbudskostAvRealisert: 0.5 },
        { navn: "Ål", region: "ukjent", vunnet: 3, tapt: 0, direkte: 17, antall: 20, timer: 27.5, snittTimer: 1.4, tilslag: 100, verdiVunnet: 2.31, tilbudskostAvRealisert: 0.3 },
        { navn: "Bø", region: "ukjent", vunnet: 4, tapt: 1, direkte: 2, antall: 7, timer: 22.5, snittTimer: 3.2, tilslag: 80, verdiVunnet: 1.43, tilbudskostAvRealisert: 1.1 },
        { navn: "Harstad", region: "ukjent", vunnet: 0, tapt: 0, direkte: 1, antall: 1, timer: 20.5, snittTimer: 20.5, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: 9.6 },
        { navn: "Lyngdal", region: "s�r", vunnet: 1, tapt: 1, direkte: 9, antall: 11, timer: 7.5, snittTimer: 0.7, tilslag: 50, verdiVunnet: 0.08, tilbudskostAvRealisert: 0.7 }
    ],

    // ============================================
    // FORRETNINGSOMR�DER - sortert etter timer (h�yest f�rst)
    // ============================================
    forretningsomrader: [
        { navn: "Reguleringsplan", vunnet: 60, tapt: 48, direkte: 69, antall: 177, timer: 2814, tilslag: 55.6, verdiVunnet: 68.35, tilbudskostAvRealisert: 2.2 },
        { navn: "Kommunal- og regional planlegging", vunnet: 34, tapt: 28, direkte: 21, antall: 83, timer: 1466.5, tilslag: 54.8, verdiVunnet: 43.55, tilbudskostAvRealisert: 2.1 },
        { navn: "Byggeplan veg", vunnet: 4, tapt: 5, direkte: 5, antall: 14, timer: 720, tilslag: 44.4, verdiVunnet: 6.64, tilbudskostAvRealisert: 4.8 },
        { navn: "Friluftsliv og naturmiljø", vunnet: 31, tapt: 9, direkte: 20, antall: 60, timer: 548, tilslag: 77.5, verdiVunnet: 18.17, tilbudskostAvRealisert: 2 },
        { navn: "Parker og Byrom", vunnet: 17, tapt: 7, direkte: 12, antall: 36, timer: 484, tilslag: 70.8, verdiVunnet: 8.83, tilbudskostAvRealisert: 2.8 },
        { navn: "Kollektivtrafikk/planlegging", vunnet: 8, tapt: 10, direkte: 0, antall: 18, timer: 385.5, tilslag: 44.4, verdiVunnet: 8.13, tilbudskostAvRealisert: 3.3 },
        { navn: "Elektro", vunnet: 12, tapt: 5, direkte: 5, antall: 22, timer: 371, tilslag: 70.6, verdiVunnet: 1.05, tilbudskostAvRealisert: 17.7 },
        { navn: "Trafikk- og transportanalyser", vunnet: 35, tapt: 6, direkte: 18, antall: 59, timer: 342, tilslag: 85.4, verdiVunnet: 6.7, tilbudskostAvRealisert: 1.6 },
        { navn: "Byutvikling (storby)", vunnet: 10, tapt: 4, direkte: 0, antall: 14, timer: 299, tilslag: 71.4, verdiVunnet: 7.9, tilbudskostAvRealisert: 2.6 },
        { navn: "Geografiske analyser", vunnet: 8, tapt: 3, direkte: 3, antall: 14, timer: 278.5, tilslag: 72.7, verdiVunnet: 2.92, tilbudskostAvRealisert: 4.6 },
        { navn: "Konsekvensutredninger", vunnet: 10, tapt: 7, direkte: 3, antall: 20, timer: 275, tilslag: 58.8, verdiVunnet: 36.82, tilbudskostAvRealisert: 0.5 },
        { navn: "Samordnet areal og transportplanlegging", vunnet: 2, tapt: 4, direkte: 4, antall: 10, timer: 263, tilslag: 33.3, verdiVunnet: 0.18, tilbudskostAvRealisert: 28.9 },
        { navn: "Nybygg - Bolig", vunnet: 10, tapt: 7, direkte: 4, antall: 21, timer: 166.5, tilslag: 58.8, verdiVunnet: 4.28, tilbudskostAvRealisert: 2.4 },
        { navn: "Mulighetsstudie", vunnet: 6, tapt: 2, direkte: 1, antall: 9, timer: 151.5, tilslag: 75, verdiVunnet: 2.13, tilbudskostAvRealisert: 4.4 },
        { navn: "Store landskapsinngrep", vunnet: 2, tapt: 1, direkte: 1, antall: 4, timer: 146.5, tilslag: 66.7, verdiVunnet: 1.25, tilbudskostAvRealisert: 7.6 },
        { navn: "Stedsutvikling", vunnet: 6, tapt: 1, direkte: 1, antall: 8, timer: 134.5, tilslag: 85.7, verdiVunnet: 2.6, tilbudskostAvRealisert: 3.6 },
        { navn: "Leke- og aktivitetsområder", vunnet: 7, tapt: 3, direkte: 5, antall: 15, timer: 133, tilslag: 70, verdiVunnet: 0.84, tilbudskostAvRealisert: 6.2 },
        { navn: "Geoinformatikk", vunnet: 1, tapt: 3, direkte: 0, antall: 4, timer: 132, tilslag: 25, verdiVunnet: 2, tilbudskostAvRealisert: 4.6 },
        { navn: "TRO - Andre offentlige bygg", vunnet: 2, tapt: 1, direkte: 1, antall: 4, timer: 122, tilslag: 66.7, verdiVunnet: 56.8, tilbudskostAvRealisert: 0.2 },
        { navn: "Havner og marine miljø", vunnet: 1, tapt: 1, direkte: 3, antall: 5, timer: 110.5, tilslag: 50, verdiVunnet: 1.2, tilbudskostAvRealisert: 4.1 },
        { navn: "Kirkegårder", vunnet: 5, tapt: 3, direkte: 6, antall: 14, timer: 95, tilslag: 62.5, verdiVunnet: 1.06, tilbudskostAvRealisert: 4 },
        { navn: "Konsept og mulighetsstudier", vunnet: 6, tapt: 4, direkte: 2, antall: 12, timer: 91.5, tilslag: 60, verdiVunnet: 1.78, tilbudskostAvRealisert: 3.1 },
        { navn: "Flyplass", vunnet: 0, tapt: 1, direkte: 0, antall: 1, timer: 88.5, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Hydrologi", vunnet: 0, tapt: 1, direkte: 1, antall: 2, timer: 78, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: 27.3 },
        { navn: "Universell Utforming", vunnet: 3, tapt: 1, direkte: 1, antall: 5, timer: 72, tilslag: 75, verdiVunnet: 1.08, tilbudskostAvRealisert: 4.5 },
        { navn: "Organisering og offentlig tjenesteproduksjon", vunnet: 1, tapt: 0, direkte: 0, antall: 1, timer: 60, tilslag: 100, verdiVunnet: 0.3, tilbudskostAvRealisert: 14 },
        { navn: "Evaluering", vunnet: 0, tapt: 2, direkte: 0, antall: 2, timer: 57.5, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Kulturminner", vunnet: 3, tapt: 0, direkte: 1, antall: 4, timer: 56, tilslag: 100, verdiVunnet: 7.25, tilbudskostAvRealisert: 0.5 },
        { navn: "TRO - Private bygg", vunnet: 0, tapt: 1, direkte: 0, antall: 1, timer: 52.5, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Avløp Slam Organisk avfall", vunnet: 0, tapt: 0, direkte: 1, antall: 1, timer: 39, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: 18.2 },
        { navn: "Bærekraft for virksomheter", vunnet: 1, tapt: 1, direkte: 1, antall: 3, timer: 37.5, tilslag: 50, verdiVunnet: 0.4, tilbudskostAvRealisert: 6.4 },
        { navn: "Nybygg - Undervisningsbygg", vunnet: 3, tapt: 1, direkte: 0, antall: 4, timer: 36.5, tilslag: 75, verdiVunnet: 2.97, tilbudskostAvRealisert: 0.9 },
        { navn: "Bane", vunnet: 1, tapt: 0, direkte: 0, antall: 1, timer: 32, tilslag: 100, verdiVunnet: 40, tilbudskostAvRealisert: 0.1 },
        { navn: "VA-transportsystemer", vunnet: 2, tapt: 0, direkte: 0, antall: 2, timer: 31.5, tilslag: 100, verdiVunnet: 2.07, tilbudskostAvRealisert: 1.1 },
        { navn: "Nybygg - Andre offentlige nybygg", vunnet: 1, tapt: 1, direkte: 2, antall: 4, timer: 29.5, tilslag: 50, verdiVunnet: 0.1, tilbudskostAvRealisert: 2.6 },
        { navn: "TRO - Undervisningsbygg og barnehager", vunnet: 0, tapt: 1, direkte: 1, antall: 2, timer: 28, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: 26.1 },
        { navn: "Sykkel", vunnet: 1, tapt: 1, direkte: 0, antall: 2, timer: 27, tilslag: 50, verdiVunnet: 0.4, tilbudskostAvRealisert: 4.7 },
        { navn: "Samfunnsøkonomi og regionaløkonomiske analyser", vunnet: 0, tapt: 2, direkte: 0, antall: 2, timer: 23, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Energi", vunnet: 2, tapt: 1, direkte: 2, antall: 5, timer: 22, tilslag: 66.7, verdiVunnet: 0.51, tilbudskostAvRealisert: 1.4 },
        { navn: "Bærekraft for infrastruktur", vunnet: 0, tapt: 1, direkte: 2, antall: 3, timer: 16.5, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: 3.3 },
        { navn: "Asplan Viak Intern", vunnet: 0, tapt: 0, direkte: 1, antall: 1, timer: 14, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: 3.3 },
        { navn: "TRO - Helsebygg", vunnet: 0, tapt: 1, direkte: 0, antall: 1, timer: 10, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Marin sektor", vunnet: 1, tapt: 0, direkte: 0, antall: 1, timer: 9, tilslag: 100, verdiVunnet: 0.7, tilbudskostAvRealisert: 0.9 },
        { navn: "VA-anlegg, byggeteknikk", vunnet: 2, tapt: 1, direkte: 0, antall: 3, timer: 9, tilslag: 66.7, verdiVunnet: 0.54, tilbudskostAvRealisert: 1.2 },
        { navn: "Natur og klimatilpasning", vunnet: 2, tapt: 0, direkte: 0, antall: 2, timer: 6, tilslag: 100, verdiVunnet: 0.04, tilbudskostAvRealisert: 10.5 },
        { navn: "Reiselivsanlegg og hoteller", vunnet: 2, tapt: 0, direkte: 0, antall: 2, timer: 6, tilslag: 100, verdiVunnet: 2.1, tilbudskostAvRealisert: 0.2 },
        { navn: "3D-visualisering", vunnet: 1, tapt: 0, direkte: 0, antall: 1, timer: 5, tilslag: 100, verdiVunnet: 0.08, tilbudskostAvRealisert: 4.4 },
        { navn: "Avfall", vunnet: 0, tapt: 0, direkte: 2, antall: 2, timer: 0, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Boliger - med høye bærekraftsmål", vunnet: 0, tapt: 1, direkte: 0, antall: 1, timer: 0, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Fjernvarme og bossug", vunnet: 0, tapt: 0, direkte: 1, antall: 1, timer: 0, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Geoteknikk, geologi", vunnet: 1, tapt: 0, direkte: 0, antall: 1, timer: 0, tilslag: 100, verdiVunnet: 0.35, tilbudskostAvRealisert: null },
        { navn: "Infrastruktur transport", vunnet: 1, tapt: 0, direkte: 0, antall: 1, timer: 0, tilslag: 100, verdiVunnet: 0.05, tilbudskostAvRealisert: null },
        { navn: "Miljø og hydrogeologi", vunnet: 0, tapt: 0, direkte: 1, antall: 1, timer: 0, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Nybygg - Annet næringsbygg", vunnet: 1, tapt: 1, direkte: 0, antall: 2, timer: 0, tilslag: 50, verdiVunnet: 0.08, tilbudskostAvRealisert: null },
        { navn: "Nybygg - Helsebygg", vunnet: 3, tapt: 0, direkte: 1, antall: 4, timer: 0, tilslag: 100, verdiVunnet: 0.82, tilbudskostAvRealisert: null },
        { navn: "Oversiktsplan veg", vunnet: 1, tapt: 0, direkte: 0, antall: 1, timer: 0, tilslag: 100, verdiVunnet: 0.3, tilbudskostAvRealisert: null },
        { navn: "Overvann som ressurs", vunnet: 0, tapt: 0, direkte: 1, antall: 1, timer: 0, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Programmering", vunnet: 0, tapt: 0, direkte: 2, antall: 2, timer: 0, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Prosjektadministrasjon", vunnet: 1, tapt: 0, direkte: 1, antall: 2, timer: 0, tilslag: 100, verdiVunnet: 0.02, tilbudskostAvRealisert: null },
        { navn: "VA-utredninger og forvaltning", vunnet: 0, tapt: 0, direkte: 1, antall: 1, timer: 0, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Vannbehandling", vunnet: 0, tapt: 0, direkte: 1, antall: 1, timer: 0, tilslag: 0, verdiVunnet: 0, tilbudskostAvRealisert: null }
    ],

    // ============================================
    // KUNDER - sortert etter timer (h�yest f�rst)
    // ============================================
    kunder: [
        { navn: "Oslo kommune v/ Bymiljøetaten", antall: 9, vunnet: 2, tapt: 3, direkte: 4, tilslag: 40, timer: 662.5, verdiVunnet: 13, tilbudskostAvRealisert: 2.3 },
        { navn: "Akershus fylkeskommune", antall: 10, vunnet: 2, tapt: 4, direkte: 4, tilslag: 33.3, timer: 618.5, verdiVunnet: 6.64, tilbudskostAvRealisert: 4.8 },
        { navn: "Lillestrøm Kommune", antall: 9, vunnet: 6, tapt: 3, direkte: 0, tilslag: 66.7, timer: 432, verdiVunnet: 11.32, tilbudskostAvRealisert: 2.7 },
        { navn: "Miljødirektoratet", antall: 7, vunnet: 5, tapt: 2, direkte: 0, tilslag: 71.4, timer: 356.5, verdiVunnet: 2.85, tilbudskostAvRealisert: 8.8 },
        { navn: "GKI Grenlandskommunenes Innkjøpsenhet", antall: 2, vunnet: 0, tapt: 2, direkte: 0, tilslag: 0, timer: 256.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Larvik kommune", antall: 7, vunnet: 5, tapt: 2, direkte: 0, tilslag: 71.4, timer: 219, verdiVunnet: 3.41, tilbudskostAvRealisert: 4.5 },
        { navn: "Bærum kommune", antall: 9, vunnet: 3, tapt: 2, direkte: 4, tilslag: 60, timer: 207, verdiVunnet: 1.8, tilbudskostAvRealisert: 6.4 },
        { navn: "Volda kommune", antall: 2, vunnet: 0, tapt: 2, direkte: 0, tilslag: 0, timer: 204.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Ruter As", antall: 6, vunnet: 3, tapt: 3, direkte: 0, tilslag: 50, timer: 201, verdiVunnet: 2.58, tilbudskostAvRealisert: 5.5 },
        { navn: "Statens vegvesen", antall: 8, vunnet: 4, tapt: 1, direkte: 3, tilslag: 80, timer: 173.5, verdiVunnet: 5.54, tilbudskostAvRealisert: 1.9 },
        { navn: "Oslobygg Kf", antall: 4, vunnet: 1, tapt: 2, direkte: 1, tilslag: 33.3, timer: 151.5, verdiVunnet: 56, tilbudskostAvRealisert: 0.2 },
        { navn: "Trondheim kommune", antall: 6, vunnet: 1, tapt: 2, direkte: 3, tilslag: 33.3, timer: 149, verdiVunnet: 0.26, tilbudskostAvRealisert: 9.3 },
        { navn: "SIGDAL KOMMUNE", antall: 6, vunnet: 3, tapt: 2, direkte: 1, tilslag: 60, timer: 146.5, verdiVunnet: 2.6, tilbudskostAvRealisert: 3.9 },
        { navn: "Vestland fylkeskommune", antall: 8, vunnet: 3, tapt: 4, direkte: 1, tilslag: 42.9, timer: 146.5, verdiVunnet: 2.6, tilbudskostAvRealisert: 3.9 },
        { navn: "OBOS Block Watne AS", antall: 4, vunnet: 2, tapt: 2, direkte: 0, tilslag: 50, timer: 123.5, verdiVunnet: 0.61, tilbudskostAvRealisert: 14.3 },
        { navn: "Statnett AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 118.5, verdiVunnet: 30, tilbudskostAvRealisert: 0.3 },
        { navn: "Skien kommune", antall: 5, vunnet: 2, tapt: 2, direkte: 1, tilslag: 50, timer: 116, verdiVunnet: 0.9, tilbudskostAvRealisert: 8.9 },
        { navn: "Telemark fylkeskommune", antall: 3, vunnet: 1, tapt: 1, direkte: 1, tilslag: 50, timer: 109.5, verdiVunnet: 1, tilbudskostAvRealisert: 5.9 },
        { navn: "Forsvarsbygg", antall: 2, vunnet: 0, tapt: 2, direkte: 0, tilslag: 0, timer: 108, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Vestfold fylkeskommune", antall: 5, vunnet: 4, tapt: 1, direkte: 0, tilslag: 80, timer: 104.5, verdiVunnet: 1.61, tilbudskostAvRealisert: 4.5 },
        { navn: "KYSTVERKET", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 104, verdiVunnet: 1.2, tilbudskostAvRealisert: 6.1 },
        { navn: "Oslo kommune - Plan- og bygningsetaten", antall: 5, vunnet: 2, tapt: 3, direkte: 0, tilslag: 40, timer: 102, verdiVunnet: 0.36, tilbudskostAvRealisert: 20.1 },
        { navn: "Kristiansund kommune", antall: 2, vunnet: 1, tapt: 1, direkte: 0, tilslag: 50, timer: 99, verdiVunnet: 0.4, tilbudskostAvRealisert: 17.3 },
        { navn: "Statkraft AS", antall: 2, vunnet: 0, tapt: 2, direkte: 0, tilslag: 0, timer: 99, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Bergen kommune - Etat for boligforvaltning", antall: 8, vunnet: 4, tapt: 4, direkte: 0, tilslag: 50, timer: 98.5, verdiVunnet: 1.92, tilbudskostAvRealisert: 3.6 },
        { navn: "OBOS Fornebu AS", antall: 4, vunnet: 2, tapt: 1, direkte: 1, tilslag: 66.7, timer: 95, verdiVunnet: 1.63, tilbudskostAvRealisert: 3.8 },
        { navn: "NORDRE FOLLO KOMMUNE", antall: 3, vunnet: 0, tapt: 3, direkte: 0, tilslag: 0, timer: 90.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "AVINOR AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 88.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Porsgrunn kommune", antall: 4, vunnet: 2, tapt: 1, direkte: 1, tilslag: 66.7, timer: 86, verdiVunnet: 1.95, tilbudskostAvRealisert: 2.7 },
        { navn: "Holmestrand kommune", antall: 2, vunnet: 0, tapt: 2, direkte: 0, tilslag: 0, timer: 85, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Askøy kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 82.5, verdiVunnet: 5, tilbudskostAvRealisert: 1.2 },
        { navn: "Vanylven Kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 77.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Statens fagskole for gartnere og blomsterdekoratører", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 77, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Herwa Eiendom AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 74.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Studentsamskipnaden SIO", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 74, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Norske Skog Saugbrugs AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 73.5, verdiVunnet: 0, tilbudskostAvRealisert: 2 },
        { navn: "Hunsfos Panorama AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 72.5, verdiVunnet: 1, tilbudskostAvRealisert: 5.1 },
        { navn: "Lørenskog kommune", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 72, verdiVunnet: 3.15, tilbudskostAvRealisert: 1.6 },
        { navn: "Nyhavna Utvikling AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 69.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "KRISTIANSAND KOMMUNE", antall: 3, vunnet: 2, tapt: 1, direkte: 0, tilslag: 66.7, timer: 67, verdiVunnet: 5.3, tilbudskostAvRealisert: 0.9 },
        { navn: "Stord kommune", antall: 2, vunnet: 0, tapt: 2, direkte: 0, tilslag: 0, timer: 67, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Sortland Kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 65.5, verdiVunnet: 1.25, tilbudskostAvRealisert: 3.7 },
        { navn: "Grimstad kommune", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 64.5, verdiVunnet: 1.05, tilbudskostAvRealisert: 4.3 },
        { navn: "Aukra kommune", antall: 2, vunnet: 0, tapt: 2, direkte: 0, tilslag: 0, timer: 63.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Nho Logistikk og Transport Region Vestlandet", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 63, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Brakar AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 61, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Finnmark Kraft", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 61, verdiVunnet: 4.2, tilbudskostAvRealisert: 1 },
        { navn: "Øvre Romerike Innkjøpssamarbeid (ØRIK)", antall: 2, vunnet: 0, tapt: 1, direkte: 1, tilslag: 0, timer: 60, verdiVunnet: 0, tilbudskostAvRealisert: 135.5 },
        { navn: "DRAMMEN KOMMUNE", antall: 2, vunnet: 1, tapt: 1, direkte: 0, tilslag: 50, timer: 59, verdiVunnet: 3, tilbudskostAvRealisert: 1.4 },
        { navn: "Ålesund kommune", antall: 2, vunnet: 1, tapt: 1, direkte: 0, tilslag: 50, timer: 59, verdiVunnet: 0.48, tilbudskostAvRealisert: 8.6 },
        { navn: "Husbanken", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 58, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Horten Kommune", antall: 3, vunnet: 1, tapt: 2, direkte: 0, tilslag: 33.3, timer: 57.5, verdiVunnet: 0.15, tilbudskostAvRealisert: 26.8 },
        { navn: "Arendal kommune", antall: 2, vunnet: 0, tapt: 1, direkte: 1, tilslag: 0, timer: 56.5, verdiVunnet: 0, tilbudskostAvRealisert: 304.2 },
        { navn: "Asker kommune", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 55.5, verdiVunnet: 0.5, tilbudskostAvRealisert: 7.8 },
        { navn: "VÆRØY KOMMUNE", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 55.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Trøndelag fylkeskommune", antall: 3, vunnet: 0, tapt: 1, direkte: 2, tilslag: 0, timer: 55, verdiVunnet: 0, tilbudskostAvRealisert: 12.2 },
        { navn: "Riksantikvaren", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 53.5, verdiVunnet: 7, tilbudskostAvRealisert: 0.5 },
        { navn: "Frydenbø Eiendom AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 52.5, verdiVunnet: 0.5, tilbudskostAvRealisert: 7.4 },
        { navn: "POB Entreprenør AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 52.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Stokkavik AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 50, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "TØNSBERG KOMMUNE", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 49.5, verdiVunnet: 0.2, tilbudskostAvRealisert: 17.3 },
        { navn: "KONGSBERG KOMMUNE", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 48, verdiVunnet: 0.8, tilbudskostAvRealisert: 4.2 },
        { navn: "FREDRIKSTAD VANN AVLØP OG RENOVASJONSFORETAK", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 46.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Hafslund Magnora Sol AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 44.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "IVestland fylkeskommune Skyss", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 42.5, verdiVunnet: 0.4, tilbudskostAvRealisert: 7.4 },
        { navn: "Agenda Kaupang AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 40.5, verdiVunnet: 3, tilbudskostAvRealisert: 0.9 },
        { navn: "Sogndal kommune", antall: 2, vunnet: 1, tapt: 1, direkte: 0, tilslag: 50, timer: 40.5, verdiVunnet: 8, tilbudskostAvRealisert: 0.4 },
        { navn: "BundeBygg AS", antall: 3, vunnet: 0, tapt: 3, direkte: 0, tilslag: 0, timer: 40, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Multiconsult Norge AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 40, verdiVunnet: 0.23, tilbudskostAvRealisert: 12.4 },
        { navn: "Veas AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 39, verdiVunnet: 0, tilbudskostAvRealisert: 18.2 },
        { navn: "Herøy Kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 38.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Vaksdal kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 38, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Borettslaget Lille Tøyen Hageby", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 37, verdiVunnet: 0.3, tilbudskostAvRealisert: 8.6 },
        { navn: "Rogaland fylkeskommune", antall: 7, vunnet: 4, tapt: 1, direkte: 2, tilslag: 80, timer: 37, verdiVunnet: 1.79, tilbudskostAvRealisert: 0.8 },
        { navn: "Tromsø Kommune", antall: 5, vunnet: 2, tapt: 1, direkte: 2, tilslag: 66.7, timer: 37, verdiVunnet: 0.2, tilbudskostAvRealisert: 2.3 },
        { navn: "Hønefoss Eiendom AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 36.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Osen kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 36.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Nordland fylkeskommune", antall: 3, vunnet: 2, tapt: 1, direkte: 0, tilslag: 66.7, timer: 35.5, verdiVunnet: 2.01, tilbudskostAvRealisert: 1.2 },
        { navn: "Smøla Nærings- og Kultursenter KF", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 35.5, verdiVunnet: 0.3, tilbudskostAvRealisert: 5.9 },
        { navn: "Kragerø Kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 33.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Anda Utvikling AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 33, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Flakstad Kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 33, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Kopparn Utvikling AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 33, verdiVunnet: 2, tilbudskostAvRealisert: 1.2 },
        { navn: "NIRAS Norge AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 32, verdiVunnet: 40, tilbudskostAvRealisert: 0.1 },
        { navn: "Norges vassdrags- og energidirektorat (NVE)", antall: 2, vunnet: 0, tapt: 2, direkte: 0, tilslag: 0, timer: 31.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Oslo kommune v/ Klimaetaten", antall: 2, vunnet: 0, tapt: 2, direkte: 0, tilslag: 0, timer: 31.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Ekebergveien 178 AS", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 31, verdiVunnet: 1.25, tilbudskostAvRealisert: 1.7 },
        { navn: "Gildeskål Kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 30.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Surnadal Kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 30.5, verdiVunnet: 0.36, tilbudskostAvRealisert: 5.9 },
        { navn: "Voss herad", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 30, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Agder fylkeskommune", antall: 3, vunnet: 0, tapt: 1, direkte: 2, tilslag: 0, timer: 29.5, verdiVunnet: 0, tilbudskostAvRealisert: 103.3 },
        { navn: "Skjervøy kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 29.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Sunnfjord kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 29.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Abakus AS", antall: 3, vunnet: 0, tapt: 3, direkte: 0, tilslag: 0, timer: 29, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Løten Kommune", antall: 5, vunnet: 1, tapt: 0, direkte: 4, tilslag: 100, timer: 29, verdiVunnet: 6, tilbudskostAvRealisert: 0.2 },
        { navn: "Mo Industripark AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 28.5, verdiVunnet: 0.5, tilbudskostAvRealisert: 4 },
        { navn: "Evje og Hornes kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 28, verdiVunnet: 0.23, tilbudskostAvRealisert: 8.7 },
        { navn: "FRIER VEST HOLDING AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 28, verdiVunnet: 2, tilbudskostAvRealisert: 1 },
        { navn: "Harakollen Utvikling AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 28, verdiVunnet: 0, tilbudskostAvRealisert: 39.2 },
        { navn: "NESODDEN KOMMUNE", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 28, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Aprova AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 27.5, verdiVunnet: 2, tilbudskostAvRealisert: 1 },
        { navn: "Oslo kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 27.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Vinje Kommune", antall: 3, vunnet: 1, tapt: 1, direkte: 1, tilslag: 50, timer: 27.5, verdiVunnet: 0.06, tilbudskostAvRealisert: 16.7 },
        { navn: "Bykle kommune", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 27, verdiVunnet: 10.3, tilbudskostAvRealisert: 0.2 },
        { navn: "Gol kommune", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 27, verdiVunnet: 1.8, tilbudskostAvRealisert: 1.1 },
        { navn: "Norsk Vind AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 27, verdiVunnet: 0.7, tilbudskostAvRealisert: 2.7 },
        { navn: "Pioneer Property Group ASA", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 26.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "AB Invest AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 25.5, verdiVunnet: 0.21, tilbudskostAvRealisert: 8.5 },
        { navn: "Norsk Gjenvinning M3 AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 24.5, verdiVunnet: 2, tilbudskostAvRealisert: 0.9 },
        { navn: "Akershus Energi AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 24, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Backe Romerike AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 22.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Hammerfest kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 22, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Haugaland Kraft AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 22, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "KS  (Kommunesektorens organisasjon)", antall: 4, vunnet: 1, tapt: 1, direkte: 2, tilslag: 50, timer: 22, verdiVunnet: 1.2, tilbudskostAvRealisert: 1.2 },
        { navn: "Kvernevikveien Invest AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 22, verdiVunnet: 1.6, tilbudskostAvRealisert: 1 },
        { navn: "Vestvågøy kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 22, verdiVunnet: 0.12, tilbudskostAvRealisert: 12.8 },
        { navn: "Artsdatabanken", antall: 5, vunnet: 3, tapt: 0, direkte: 2, tilslag: 100, timer: 21.5, verdiVunnet: 1.44, tilbudskostAvRealisert: 0.9 },
        { navn: "Kjellandsheia AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 21, verdiVunnet: 0, tilbudskostAvRealisert: 8.2 },
        { navn: "Nesbyen Kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 21, verdiVunnet: 0.25, tilbudskostAvRealisert: 5.9 },
        { navn: "KOMMUNAL- OG DISTRIKTSDEPARTEMENTET", antall: 3, vunnet: 0, tapt: 2, direkte: 1, tilslag: 0, timer: 20.5, verdiVunnet: 0, tilbudskostAvRealisert: 4.8 },
        { navn: "A Markussen AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 20, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Bertel O. Steen Eiendom AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 20, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Færder kommune", antall: 8, vunnet: 7, tapt: 0, direkte: 1, tilslag: 100, timer: 19.5, verdiVunnet: 4.81, tilbudskostAvRealisert: 0.3 },
        { navn: "Circle K Norge AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 19, verdiVunnet: 1, tilbudskostAvRealisert: 1.3 },
        { navn: "Stiftelsen Betanien (Bergen)", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 19, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Øster Hus AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 19, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Galterud Utvikling AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 18.5, verdiVunnet: 1, tilbudskostAvRealisert: 1.3 },
        { navn: "Birkenes kommune", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 17.5, verdiVunnet: 0.55, tilbudskostAvRealisert: 2.2 },
        { navn: "Notodden kommune", antall: 2, vunnet: 1, tapt: 1, direkte: 0, tilslag: 50, timer: 17, verdiVunnet: 0, tilbudskostAvRealisert: 340 },
        { navn: "Risør kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 16.5, verdiVunnet: 0.68, tilbudskostAvRealisert: 1.7 },
        { navn: "Stiftelsen Design og Arkitektur Norge", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 16.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Kongsberg Utvikling AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 16, verdiVunnet: 0.4, tilbudskostAvRealisert: 2.8 },
        { navn: "Drømtorp AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 15.5, verdiVunnet: 0.3, tilbudskostAvRealisert: 3.6 },
        { navn: "INNLANDET FYLKESKOMMUNE", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 15.5, verdiVunnet: 5, tilbudskostAvRealisert: 0.2 },
        { navn: "Røyken Grovfyllplass AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 15.5, verdiVunnet: 0, tilbudskostAvRealisert: 1.1 },
        { navn: "Gjerdrum Kommune", antall: 4, vunnet: 3, tapt: 0, direkte: 1, tilslag: 100, timer: 15, verdiVunnet: 0.47, tilbudskostAvRealisert: 1.1 },
        { navn: "Indre Østfold kommune", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 14.5, verdiVunnet: 0.4, tilbudskostAvRealisert: 1.6 },
        { navn: "Khan Cs", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 14.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Pir II Oslo AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 14, verdiVunnet: 0.4, tilbudskostAvRealisert: 2.5 },
        { navn: "Bergen Byfortetting AS", antall: 4, vunnet: 4, tapt: 0, direkte: 0, tilslag: 100, timer: 13.5, verdiVunnet: 0.27, tilbudskostAvRealisert: 3.6 },
        { navn: "Skien Kirkelige Fellesråd", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 13.5, verdiVunnet: 0, tilbudskostAvRealisert: 5.4 },
        { navn: "Synnfjell Dokksfløy utmarkslag", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 13.5, verdiVunnet: 0.7, tilbudskostAvRealisert: 1.4 },
        { navn: "Gjerstad kommune", antall: 4, vunnet: 2, tapt: 1, direkte: 1, tilslag: 66.7, timer: 13, verdiVunnet: 0.3, tilbudskostAvRealisert: 2.3 },
        { navn: "Isachsen Anlegg AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 13, verdiVunnet: 0, tilbudskostAvRealisert: 3.9 },
        { navn: "Modalen kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 13, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Åseral kommune", antall: 3, vunnet: 2, tapt: 1, direkte: 0, tilslag: 66.7, timer: 13, verdiVunnet: 0.32, tilbudskostAvRealisert: 2.8 },
        { navn: "Kristiansand Havn IKS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 12.5, verdiVunnet: 0.3, tilbudskostAvRealisert: 2.9 },
        { navn: "Trysilhus Areal AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 12.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Ann Elisabeth Lunde", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 12, verdiVunnet: 0.08, tilbudskostAvRealisert: 10.5 },
        { navn: "Hydro Aluminium AS Hydro Energi Sogn", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 12, verdiVunnet: 0.25, tilbudskostAvRealisert: 3.4 },
        { navn: "Lab AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 12, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Lund Nydalen AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 12, verdiVunnet: 0.35, tilbudskostAvRealisert: 2.4 },
        { navn: "Øygarden kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 12, verdiVunnet: 1.9, tilbudskostAvRealisert: 0.4 },
        { navn: "Hægebostad Kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 11.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Charlottenlund Lokalsenter AS", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 10.5, verdiVunnet: 0.8, tilbudskostAvRealisert: 0.9 },
        { navn: "Frogn Kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 10.5, verdiVunnet: 0.4, tilbudskostAvRealisert: 1.8 },
        { navn: "Østfold fylkeskommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 10.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Øystre Slidre Kommune", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 10.5, verdiVunnet: 0.65, tilbudskostAvRealisert: 1.1 },
        { navn: "Backe Oppland AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 10, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Midt-telemark Kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 10, verdiVunnet: 0.2, tilbudskostAvRealisert: 3.5 },
        { navn: "Spennarmering As", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 10, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Bergersen Arkitekter AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 9.5, verdiVunnet: 0, tilbudskostAvRealisert: 3.3 },
        { navn: "Direktoratet for samfunnssikkerhet og beredskap (DSB)", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 9.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Austevoll kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 9, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Oslo Handelsstands Forening", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 9, verdiVunnet: 0.28, tilbudskostAvRealisert: 2.3 },
        { navn: "Ravnkloa AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 9, verdiVunnet: 0.15, tilbudskostAvRealisert: 4.2 },
        { navn: "Hallsettoppen Eiendom AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 8.5, verdiVunnet: 0.14, tilbudskostAvRealisert: 4.4 },
        { navn: "Jernbanedirektoratet", antall: 2, vunnet: 0, tapt: 1, direkte: 1, tilslag: 0, timer: 8.5, verdiVunnet: 0, tilbudskostAvRealisert: 4 },
        { navn: "Skanska Husfabrikken AS", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 8.5, verdiVunnet: 0.1, tilbudskostAvRealisert: 2.8 },
        { navn: "Årdal Kyrkjelege Fellesråd", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 8.5, verdiVunnet: 0.13, tilbudskostAvRealisert: 4.8 },
        { navn: "Agderplan AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 8, verdiVunnet: 0, tilbudskostAvRealisert: 18.1 },
        { navn: "Kjeldaas AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 8, verdiVunnet: 1.2, tilbudskostAvRealisert: 0.5 },
        { navn: "Oslo kommune v/ Vann- og avløpsetaten", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 8, verdiVunnet: 0.35, tilbudskostAvRealisert: 0.3 },
        { navn: "Østerdalsgata 1 prosjekt AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 8, verdiVunnet: 0.29, tilbudskostAvRealisert: 1.9 },
        { navn: "Fredensborg Fritid Flå AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 7.5, verdiVunnet: 0.2, tilbudskostAvRealisert: 2.6 },
        { navn: "Geoforum", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 7.5, verdiVunnet: 0.04, tilbudskostAvRealisert: 12.2 },
        { navn: "HENT AS", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 7.5, verdiVunnet: 0.02, tilbudskostAvRealisert: 1.8 },
        { navn: "Inger June Moi Mydland", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 7.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Nes Kommune (Årnes)", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 7.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Hovet og Sudndalen Grunneigarlag", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 7, verdiVunnet: 0.1, tilbudskostAvRealisert: 4.9 },
        { navn: "Ruta Entreprenør AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 7, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Rælingen Kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 7, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Betonmast Innlandet AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 6.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Dr Techn Olav Olsen AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 6.5, verdiVunnet: 0, tilbudskostAvRealisert: 6.8 },
        { navn: "Bergen Havn AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 6, verdiVunnet: 0.2, tilbudskostAvRealisert: 2.1 },
        { navn: "Boxs Arkitektstudio AS", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 6, verdiVunnet: 0.05, tilbudskostAvRealisert: 9.1 },
        { navn: "Coera AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 6, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Fredensborg Bolig AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 6, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Fredensborg Fritid AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 6, verdiVunnet: 2, tilbudskostAvRealisert: 0.2 },
        { navn: "Kongsberg Entreprenør AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 6, verdiVunnet: 0, tilbudskostAvRealisert: 1.1 },
        { navn: "Mibau Stema Norge AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 6, verdiVunnet: 0, tilbudskostAvRealisert: 0.4 },
        { navn: "Nils Anders Holte", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 6, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Nord-Fron Kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 6, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "NorgesGruppen Eiendom AS", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 6, verdiVunnet: 0.17, tilbudskostAvRealisert: 2.3 },
        { navn: "Rett Hjem bolig AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 6, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "TUIL AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 6, verdiVunnet: 0, tilbudskostAvRealisert: 0.1 },
        { navn: "Yttersø Forvaltning AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 5.5, verdiVunnet: 0.03, tilbudskostAvRealisert: 12.8 },
        { navn: "Caissa Consult AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 5, verdiVunnet: 0.15, tilbudskostAvRealisert: 2.3 },
        { navn: "Drageland AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Funnemark Eiendom AS", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 5, verdiVunnet: 0.08, tilbudskostAvRealisert: 3.9 },
        { navn: "Hageanlegg AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 5, verdiVunnet: 0, tilbudskostAvRealisert: 2.3 },
        { navn: "INEO Eiendom AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 5, verdiVunnet: 0.54, tilbudskostAvRealisert: 0.7 },
        { navn: "Knud Bryns vei 1 AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 5, verdiVunnet: 0.28, tilbudskostAvRealisert: 1.3 },
        { navn: "Lilleby Eiendom AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 5, verdiVunnet: 0, tilbudskostAvRealisert: 1.8 },
        { navn: "S4sport AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 5, verdiVunnet: 0.08, tilbudskostAvRealisert: 4.4 },
        { navn: "Sogneprest Holts Vei 2 AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 5, verdiVunnet: 0, tilbudskostAvRealisert: 2.4 },
        { navn: "Akersgata 73 AS", antall: 2, vunnet: 0, tapt: 0, direkte: 2, tilslag: 0, timer: 4.5, verdiVunnet: 0, tilbudskostAvRealisert: 1.3 },
        { navn: "Hustadvika kommune", antall: 2, vunnet: 0, tapt: 1, direkte: 1, tilslag: 0, timer: 4.5, verdiVunnet: 0, tilbudskostAvRealisert: 1.3 },
        { navn: "Høgevarde as", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 4.5, verdiVunnet: 0, tilbudskostAvRealisert: 3.2 },
        { navn: "Ims Group AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 4.5, verdiVunnet: 0.16, tilbudskostAvRealisert: 2 },
        { navn: "Sirdal Kommune", antall: 2, vunnet: 0, tapt: 1, direkte: 1, tilslag: 0, timer: 4.5, verdiVunnet: 0, tilbudskostAvRealisert: 0.9 },
        { navn: "Sula kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 4.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "AS Hibas", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 4, verdiVunnet: 0.07, tilbudskostAvRealisert: 4 },
        { navn: "Backe Rogaland AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 4, verdiVunnet: 2.2, tilbudskostAvRealisert: 0.1 },
        { navn: "Berntsen Plan & Oppmåling AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 4, verdiVunnet: 0.14, tilbudskostAvRealisert: 2 },
        { navn: "Bico Bygg og Innredning AS", antall: 2, vunnet: 1, tapt: 1, direkte: 0, tilslag: 50, timer: 4, verdiVunnet: 0.04, tilbudskostAvRealisert: 7 },
        { navn: "Helge Bakken", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 4, verdiVunnet: 0.21, tilbudskostAvRealisert: 1.3 },
        { navn: "Håkon Vestberg", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 4, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Lørenskog kirkelig fellesråd", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 4, verdiVunnet: 0.5, tilbudskostAvRealisert: 0.6 },
        { navn: "Major og Advokat Eivind Eckbos Legat Sti", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 4, verdiVunnet: 0, tilbudskostAvRealisert: 2 },
        { navn: "Tero Anlegg AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 4, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Ålesund Tomteselskap AS", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 4, verdiVunnet: 0.06, tilbudskostAvRealisert: 3.5 },
        { navn: "K102 Eiendom AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 3.5, verdiVunnet: 0, tilbudskostAvRealisert: 2.6 },
        { navn: "Mora Invest AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 3.5, verdiVunnet: 0.07, tilbudskostAvRealisert: 3.8 },
        { navn: "Hege Wingaard", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 3, verdiVunnet: 0.05, tilbudskostAvRealisert: 4.2 },
        { navn: "Kongsberg kirkelige fellesråd", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 3, verdiVunnet: 0.07, tilbudskostAvRealisert: 3.2 },
        { navn: "Sandefjord Kommune", antall: 3, vunnet: 3, tapt: 0, direkte: 0, tilslag: 100, timer: 3, verdiVunnet: 1.7, tilbudskostAvRealisert: 0.1 },
        { navn: "Stavanger kommune", antall: 2, vunnet: 1, tapt: 1, direkte: 0, tilslag: 50, timer: 3, verdiVunnet: 0.1, tilbudskostAvRealisert: 2.1 },
        { navn: "Tinde Utvikling Stryn AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 3, verdiVunnet: 0.11, tilbudskostAvRealisert: 1.9 },
        { navn: "Vardåsveien Bolig AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 3, verdiVunnet: 0.2, tilbudskostAvRealisert: 1.1 },
        { navn: "Alver kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 2.5, verdiVunnet: 0.1, tilbudskostAvRealisert: 1.8 },
        { navn: "Atlas Eiendom AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 2.5, verdiVunnet: 0.08, tilbudskostAvRealisert: 2.2 },
        { navn: "FARO AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 2.5, verdiVunnet: 0.11, tilbudskostAvRealisert: 1.6 },
        { navn: "Larvik Impregneringskompani AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 2.5, verdiVunnet: 0.08, tilbudskostAvRealisert: 2.2 },
        { navn: "Ringerike kirkelige fellesråd", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 2.5, verdiVunnet: 0, tilbudskostAvRealisert: 1.8 },
        { navn: "Ringvoll Næringspark AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 2.5, verdiVunnet: 0.12, tilbudskostAvRealisert: 1.5 },
        { navn: "Veidekke Entreprenør AS", antall: 4, vunnet: 2, tapt: 0, direkte: 2, tilslag: 100, timer: 2.5, verdiVunnet: 0.34, tilbudskostAvRealisert: 0.4 },
        { navn: "Anders Ostad", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 2, verdiVunnet: 0.06, tilbudskostAvRealisert: 2.5 },
        { navn: "Barlindhaug Eiendom AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 2, verdiVunnet: 0.02, tilbudskostAvRealisert: 9.3 },
        { navn: "Eiffage Norge", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 2, verdiVunnet: 0.05, tilbudskostAvRealisert: 0.6 },
        { navn: "Geitmyrsveien 7d AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 2, verdiVunnet: 0, tilbudskostAvRealisert: 3.5 },
        { navn: "Horten Industripark AS", antall: 3, vunnet: 2, tapt: 0, direkte: 1, tilslag: 100, timer: 2, verdiVunnet: 0.6, tilbudskostAvRealisert: 0.2 },
        { navn: "Insenti AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 2, verdiVunnet: 0.09, tilbudskostAvRealisert: 1.5 },
        { navn: "Rabb84 AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 2, verdiVunnet: 0.28, tilbudskostAvRealisert: 0.5 },
        { navn: "Vedal Entreprenør AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 2, verdiVunnet: 0.1, tilbudskostAvRealisert: 1.4 },
        { navn: "Angvik Prosjektering As", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 1.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Buskerud fylkeskommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 1.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Kile Stokholm Arkitekter AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 1.5, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Sit (Studentsamskipnaden i Gjøvik, Ålesund og Trondheim)", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 1.5, verdiVunnet: 0, tilbudskostAvRealisert: 0.2 },
        { navn: "EvoTek AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 1, verdiVunnet: 0.09, tilbudskostAvRealisert: 0.8 },
        { navn: "FDV Troms AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 1, verdiVunnet: 0.03, tilbudskostAvRealisert: 2.3 },
        { navn: "Foldvik AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 1, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Glenn Braaten", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 1, verdiVunnet: 0.15, tilbudskostAvRealisert: 0.5 },
        { navn: "Hjertnes Bolig Ii AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 1, verdiVunnet: 0, tilbudskostAvRealisert: 1.6 },
        { navn: "Idea Bolig AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 1, verdiVunnet: 0.06, tilbudskostAvRealisert: 1.2 },
        { navn: "Modum Motorsportklubb", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 1, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "NP Utvikling AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 1, verdiVunnet: 0.09, tilbudskostAvRealisert: 0.8 },
        { navn: "Sørnesvågen AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 1, verdiVunnet: 0.04, tilbudskostAvRealisert: 1.7 },
        { navn: "Tinn kommune", antall: 2, vunnet: 0, tapt: 0, direkte: 2, tilslag: 0, timer: 1, verdiVunnet: 0, tilbudskostAvRealisert: 0.1 },
        { navn: "Øvre Utsikten AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 1, verdiVunnet: 0, tilbudskostAvRealisert: 1.8 },
        { navn: "Gjesdal Kommune", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0.5, verdiVunnet: 0, tilbudskostAvRealisert: 0.2 },
        { navn: "Vendkvern Brug Per Gunnar Thomassen", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0.5, verdiVunnet: 0.01, tilbudskostAvRealisert: 2.9 },
        { navn: "Vestby Kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0.5, verdiVunnet: 0.4, tilbudskostAvRealisert: 0.1 },
        { navn: "AE Lier AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "AF GRUPPEN ASA", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "AF Tangen Allé Entreprenør ANS", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.35, tilbudskostAvRealisert: null },
        { navn: "ANEO AS", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 0, verdiVunnet: 0.4, tilbudskostAvRealisert: null },
        { navn: "AS Assuransegården", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.33, tilbudskostAvRealisert: null },
        { navn: "AS Thor Dahl", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.05, tilbudskostAvRealisert: null },
        { navn: "Agder Renovasjon IKS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Allstad Eiendomsutvikling AS", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.59, tilbudskostAvRealisert: null },
        { navn: "Anders Kristian Salvesen", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Anita Bulæg", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Anskaffelser i Akershus, Buskerud og Østfold KO", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.7, tilbudskostAvRealisert: null },
        { navn: "Arkitektkontoret Henning Karlsen AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Arkitektkontoret Schjelderup & Gram AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.04, tilbudskostAvRealisert: null },
        { navn: "Arkitektur og Designhøgskolen i Oslo AHO", antall: 2, vunnet: 0, tapt: 0, direkte: 2, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Aurskog-Høland kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.02, tilbudskostAvRealisert: null },
        { navn: "Avinet AS", antall: 2, vunnet: 0, tapt: 0, direkte: 2, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "BIO Eiendom AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.02, tilbudskostAvRealisert: null },
        { navn: "BIR Infrastruktur AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "BRG Entreprenør AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.75, tilbudskostAvRealisert: null },
        { navn: "Bakke AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Bakkestølvegen 81 AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Bjørntvedtvegen 156 AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Bliksåsen Panorama AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Bne Paradis 1 AS", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 0, verdiVunnet: 0.05, tilbudskostAvRealisert: null },
        { navn: "Bodø Kirkelige Fellesråd", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Boligprodusentenes Forening", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Braaten Eiendom AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.03, tilbudskostAvRealisert: null },
        { navn: "Breidok Borettslag", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Brødrene Alseth AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Brønnøy Kalk AS", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 2.1, tilbudskostAvRealisert: null },
        { navn: "Bøylestad Energipark AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "COOP Midt-Norge SA", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Consto AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.01, tilbudskostAvRealisert: null },
        { navn: "DNT Telemark", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Deep Wind Offshore AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Dirdal Idrettslag", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Ditt Nye Hjem AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.06, tilbudskostAvRealisert: null },
        { navn: "Dpend Eiendom AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Drangedal Kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.05, tilbudskostAvRealisert: null },
        { navn: "Dronning Mauds Minne Høgskole for barnehagelærerutdanning", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Dronning Ragnhilds Vei AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.1, tilbudskostAvRealisert: null },
        { navn: "EVVER AS", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.19, tilbudskostAvRealisert: null },
        { navn: "Egdastrek AS", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 0, verdiVunnet: 0.08, tilbudskostAvRealisert: null },
        { navn: "Eggen Arkitekter AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Eikelia AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Ekelund Utvikling AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.03, tilbudskostAvRealisert: null },
        { navn: "Ekstrand Eiendom AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.04, tilbudskostAvRealisert: null },
        { navn: "Elisabeth Goverud", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Espern Eiendom As", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.02, tilbudskostAvRealisert: null },
        { navn: "Evas Grønne Hage AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "FINNMARK FYLKESKOMMUNE", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 13, tilbudskostAvRealisert: null },
        { navn: "FLAKSTAD SOKN", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.31, tilbudskostAvRealisert: null },
        { navn: "Filosofilandskap Lofoten AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.24, tilbudskostAvRealisert: null },
        { navn: "Fiskebrygga Eiendom AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.1, tilbudskostAvRealisert: null },
        { navn: "Fiskergata 22 Svolvær AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.05, tilbudskostAvRealisert: null },
        { navn: "Flakvarp Båtforening", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Flekkefjord Kommune", antall: 3, vunnet: 0, tapt: 0, direkte: 3, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Flå Kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.25, tilbudskostAvRealisert: null },
        { navn: "Food Folk Norge AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Forsand Sandkompani AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Fredrikstad Kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Frost Eiendom AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Geilo Mekaniske Håkon Hallingstad", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Gjøvik Kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.3, tilbudskostAvRealisert: null },
        { navn: "Gol og Herad sokneråd", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Gopledal Båtforening", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "HIG48 AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.02, tilbudskostAvRealisert: null },
        { navn: "HK Utvikling AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Haandverkerne AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.14, tilbudskostAvRealisert: null },
        { navn: "Hagen Gjenvinning AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.11, tilbudskostAvRealisert: null },
        { navn: "Halden Kommunale Pensjonskasse", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.5, tilbudskostAvRealisert: null },
        { navn: "Hallingdal Hytteservice AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Halse Eiendom AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Harald Halvorsen", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Harald Moræus-Hanssen", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Hauk Sveinsson Utvikling AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Heidelberg Materials Tilslag Norge AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.15, tilbudskostAvRealisert: null },
        { navn: "Heimgard bolig AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Hill Eiendom AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Hjartdal kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.2, tilbudskostAvRealisert: null },
        { navn: "Hol Kommune", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Horgmo Eiendom AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Horten Havn", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 0, verdiVunnet: 0.15, tilbudskostAvRealisert: null },
        { navn: "Horten Havnepark AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.05, tilbudskostAvRealisert: null },
        { navn: "Horten kirkelige fellesråd", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Hydro Rein Norway Holding AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Jan Willy Løken", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Jåttåvågen Brygge AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.58, tilbudskostAvRealisert: null },
        { navn: "KLP Eiendom Trondheim As", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Karlsøy kommune", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 1.6, tilbudskostAvRealisert: null },
        { navn: "Karmøy Kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Kilden Menighet", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Klepp Mek AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.09, tilbudskostAvRealisert: null },
        { navn: "Kongsberg Næringsparkutvikling AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Kragerøfjorden Utvikling AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Kuskjær AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Kvinesdal kommune", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Langgrunn Næringsutvikling AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Lars Bjørnø", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Larvik Havn KF", antall: 2, vunnet: 0, tapt: 0, direkte: 2, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Leif Tollehaugen", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.36, tilbudskostAvRealisert: null },
        { navn: "Lillehammer Kommune", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Lindesnes kommune", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Lister nyskaping AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Lumber AS", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.45, tilbudskostAvRealisert: null },
        { navn: "MOWI ASA", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Marcus Thranes Vei 2 Bolig AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Marvika Atrium AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Marviksletta Utvikling AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Melkekannan Fjellhytter AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Merethe Rostad", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Midtre Gauldal Kommune", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Mimir AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Møre og Romsdal Fylkeskommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.3, tilbudskostAvRealisert: null },
        { navn: "NTNU", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Nannestad kommune", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Naturrestaurering AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Nesfjellet Prosjektutvikling AS", antall: 2, vunnet: 0, tapt: 0, direkte: 2, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Nidaros Domkirkes Restaureringsarbeider", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Nome Kyrkjelege Fellesråd", antall: 2, vunnet: 0, tapt: 0, direkte: 2, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Nordkappregionen Havn IKS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Nordveggen AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.09, tilbudskostAvRealisert: null },
        { navn: "Norges Friidrettsforbund", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.02, tilbudskostAvRealisert: null },
        { navn: "Norgeshus AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.08, tilbudskostAvRealisert: null },
        { navn: "Olav Espgard", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Ole Kristian Strand", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.01, tilbudskostAvRealisert: null },
        { navn: "Olsrød Park AS", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Opsjon Syd AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.09, tilbudskostAvRealisert: null },
        { navn: "Oslo Works AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Ove Arup & Partners Danmark A/S", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "PK Entreprenør AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Pjberget Per Jørgen Berget", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Planor bolig AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.25, tilbudskostAvRealisert: null },
        { navn: "Primhovda Sør AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Pth Eiendom AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Randaberg kommune", antall: 2, vunnet: 0, tapt: 0, direkte: 2, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Re Energi AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.1, tilbudskostAvRealisert: null },
        { navn: "Rugsland Sandtak AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Runa A. Brekke Gjerland", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.04, tilbudskostAvRealisert: null },
        { navn: "STATSBYGG", antall: 3, vunnet: 3, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.6, tilbudskostAvRealisert: null },
        { navn: "STEIN HALVORSEN ARKITEKTER AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.04, tilbudskostAvRealisert: null },
        { navn: "Sabima", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Salangen kommune", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.03, tilbudskostAvRealisert: null },
        { navn: "Sandnes kommune", antall: 3, vunnet: 1, tapt: 2, direkte: 0, tilslag: 33.3, timer: 0, verdiVunnet: 0.3, tilbudskostAvRealisert: null },
        { navn: "Seabrokers Eiendom AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.04, tilbudskostAvRealisert: null },
        { navn: "Seby AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.07, tilbudskostAvRealisert: null },
        { navn: "Sentrumaksen AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Setra Surnadal AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.03, tilbudskostAvRealisert: null },
        { navn: "Siero AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Skaaret Eiendom AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.03, tilbudskostAvRealisert: null },
        { navn: "Skalér AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Skanska Norge AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.4, tilbudskostAvRealisert: null },
        { navn: "Skaret Eiendom AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Skeie Eiendom AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.3, tilbudskostAvRealisert: null },
        { navn: "Skigeilo Utvikling AS", antall: 2, vunnet: 0, tapt: 0, direkte: 2, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Skoleveien 9-11 AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Snømyra barnehage SA", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Sola Strand Hotel AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 1.15, tilbudskostAvRealisert: null },
        { navn: "Solbråveien AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.11, tilbudskostAvRealisert: null },
        { navn: "Solon Bolig AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Spir Arkitekter AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "St Olavs Gate Terrasse AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Statsforvaltaren i Møre og Romsdal", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 1.3, tilbudskostAvRealisert: null },
        { navn: "Statsforvalteren i Vestfold og Telemark", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Statskog SF", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.2, tilbudskostAvRealisert: null },
        { navn: "Stavanger Parkeringsselskap Kf", antall: 2, vunnet: 1, tapt: 0, direkte: 1, tilslag: 100, timer: 0, verdiVunnet: 0.05, tilbudskostAvRealisert: null },
        { navn: "Strand AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.06, tilbudskostAvRealisert: null },
        { navn: "Strand Kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Strategisk Ruteplan AS", antall: 2, vunnet: 2, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.05, tilbudskostAvRealisert: null },
        { navn: "Sveggen Næringspark AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Sør-Varanger kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "TVB Bolig AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Tekna Drammen Avdeling", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.01, tilbudskostAvRealisert: null },
        { navn: "Tom-Frode Johansen", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.1, tilbudskostAvRealisert: null },
        { navn: "Trafo Arkitektur AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.01, tilbudskostAvRealisert: null },
        { navn: "Trygve Ekelund", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Trygve J Sjøen AS", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Tvedestrand kommune", antall: 1, vunnet: 0, tapt: 1, direkte: 0, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Ulvik herad", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.07, tilbudskostAvRealisert: null },
        { navn: "Universitetet i Stavanger", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.02, tilbudskostAvRealisert: null },
        { navn: "Universitetet i Tromsø - Norges arktiske universitet", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Vennesla kommune", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Verdalskalk AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.08, tilbudskostAvRealisert: null },
        { navn: "Vestby Senterutvikling AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.1, tilbudskostAvRealisert: null },
        { navn: "Voss Fallskjermklubb", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Vågen & Hansen Utemiljø AS", antall: 2, vunnet: 1, tapt: 1, direkte: 0, tilslag: 50, timer: 0, verdiVunnet: 0.02, tilbudskostAvRealisert: null },
        { navn: "WSP Norge AS", antall: 2, vunnet: 0, tapt: 0, direkte: 2, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Wangberg Vvs AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.06, tilbudskostAvRealisert: null },
        { navn: "Ål Kommune", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null },
        { navn: "Årnes Brygge AS", antall: 1, vunnet: 1, tapt: 0, direkte: 0, tilslag: 100, timer: 0, verdiVunnet: 0.02, tilbudskostAvRealisert: null },
        { navn: "Øster Hus Invest AS", antall: 3, vunnet: 1, tapt: 1, direkte: 1, tilslag: 50, timer: 0, verdiVunnet: 1.95, tilbudskostAvRealisert: null },
        { navn: "Øyer Kommune", antall: 1, vunnet: 0, tapt: 0, direkte: 1, tilslag: 0, timer: 0, verdiVunnet: 0, tilbudskostAvRealisert: null }
    ],

    // ============================================
    // ST�RSTE TAPTE TILBUD
    // ============================================
    storsteTapte: [
        // Denne m� hentes fra Master APL 2025 arket - filtrert p� Status=Tapt, sortert etter verdi
    ]
};
